# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-22 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnaa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='number_of_critical_points',
            new_name='critical_points_count',
        ),
        migrations.AddField(
            model_name='route',
            name='critical_points_list',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
